version: '3.5'
services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: "typoteka.notify.fakesmtp"
    hostname: "fakesmtp"
    ports:
      - "5025:5025"
      - "1083:5080"

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: typoteka.notify.rabbitmq
    ports:
      - '1084:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo
    container_name: typoteka.notify.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: typoteka-notify
    ports:
      - 27018:27017
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/typoteka-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5
